### ISSUE TITLE
Unplayable item in script but works on ipad/web browser

### ISSUE THREAD

**Issue by itpowerse** [kokangit/xbmc-swefilmer#11]
Hi,

Great work, issues solved fast!!! However, I found a new one that might be a bit tricky to fix? It appears that some titles have some sort of HTML5 wrapper that cause the script to being unable to play the video file. 

If you decode the hex data in the html "sources" attribute listed in the html code below you get the true video URLs:

<code><preview>
sources: [{"file":"http://217.20.157.197/?id=11916806734&expires=1420588732162&type=3&ct=0&sig=5fe7d9be2b5130e1ec85b6965707365a606ec853&clientType=0", "label":"720","type":"mp4"},{"file":"http://217.20.157.204/?id=11916806734&expires=1420588732162&type=2&ct=0&sig=10b2236a4da14046fc221ebdd70edeccbd5429d3&clientType=0", "label":"480","type":"mp4"},{"file":"http://217.20.145.40/?id=11916806734&expires=1420588732162&type=1&ct=0&sig=606c27e402bcae23918eaaacc9ced28a47291614&clientType=0", "label":"360","type":"mp4"},{"file":"http://217.20.153.80/?id=11916806734&expires=1420588732162&type=0&ct=0&sig=c05fdfbaeff8a61c45677bbce1b16305d635aab1&clientType=0", "label":"240","type":"mp4"},{"file":"http://217.20.145.36/?id=11916806734&expires=1420588732162&type=4&ct=0&sig=a3ef3749a0f3e0c5fb8134db1fb17616c62d4480&clientType=0", "label":"144","type":"mp4"}],
</code></preview>

Below is xbmc.log file example (XBMC 13.2/ATV2 script 1.6) and the resulting video URL html code:

<pre><code>
00:57:21 T:148201472  NOTICE: -->Python Interpreter Initialized<--
00:57:21 T:148201472  NOTICE: get_url (video.html): http://www.swefilmer.com/boyhood-2014/boyhood-2014-video_9aaab8c31.html
00:57:22 T:148201472  NOTICE: scrape_video: description=['En historia om ett fr\xc3\xa5nskilt par som f\xc3\xb6rs\xc3\xb6ker uppfostra sin unge son.\nBer\xc3\xa4ttelsen f\xc3\xb6ljer pojken i tolv \xc3\xa5r och unders\xc3\xb6ker hans relation med\nsina f\xc3\xb6r\xc3\xa4ldrar n\xc3\xa4r han v\xc3\xa4xer upp. Filmad i korta perioder mellan 2002\noch 2013.']
00:57:22 T:148201472  NOTICE: scrape_video: img=['http://i61.tinypic.com/15d12dz.jpg']
00:57:22 T:148201472  NOTICE: found garbled player
00:57:22 T:148201472  NOTICE: scrape_video: html=<iframe scrolling="no" width="500" height="370" src="http://swefilmer.info/od/fast.php?i1=MIA9QwZbrbV7QVNCeiJmpU%2BIzVM9xCaiKREJP3IySD0%3D&i0=1d003ff98beb36acc14e49db7a054462" frameborder="0" allowfullscreen></iframe>
00:57:22 T:148201472  NOTICE: scrape_video: url=http://swefilmer.info/od/fast.php?i1=MIA9QwZbrbV7QVNCeiJmpU%2BIzVM9xCaiKREJP3IySD0%3D&i0=1d003ff98beb36acc14e49db7a054462
00:57:22 T:148201472  NOTICE: get_url (document.html): http://swefilmer.info/od/fast.php?i1=MIA9QwZbrbV7QVNCeiJmpU%2BIzVM9xCaiKREJP3IySD0%3D&i0=1d003ff98beb36acc14e49db7a054462
00:57:22 T:148201472  NOTICE: scrape_video_registered: search for videoSrc
00:57:28 T:120094720   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.swefilmer/?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fboyhood-2014%2Fboyhood-2014-video_9aaab8c31.html&logged_in=True]
00:57:28 T:146923520  NOTICE: Thread BackgroundLoader start, auto delete: false
</pre></code>

HTML code:
<pre><code>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		    
		    <script type="text/javascript" src="./fast.php_files/jquery-1.10.2.min.js"></script>
		    <script type="text/javascript" src="./fast.php_files/jwplayer.js"></script>
		    <script type="text/javascript">jwplayer.key="8EUAFOk/3tCF7h1TZyzPFH916gBw6Yvr3dLNTJ5D5mlU6BhDfx6nxw==";</script>
		    <style type="text/css">
		        html,body {margin:0px;padding:0px;height: 100% !important;}
		        #player {position:relative;width:100% !important;height: 100% !important;}
		        a {cursor:pointer}
		    </style>
		<script src="./fast.php_files/jwpsrv.js"></script><script src="./fast.php_files/jwpsrv_frq.js"></script><style type="text/css"></style></head>
		<body bgcolor="#000000">
		    <div id="player_wrapper" style="position: relative; display: block; width: 100%; height: 100%;"><a id="beforeswfanchor0" href="http://swefilmer.info/od/fast.php?i1=MIA9QwZbrbV7QVNCeiJmpU%2BIzVM9xCaiKREJP3IySD0%3D&i0=1d003ff98beb36acc14e49db7a054462#player" tabindex="-1" title="Flash start" style="border:0;clip:rect(0 0 0 0);display:block;height:1px;margin:-1px;outline:none;overflow:hidden;padding:0;position:absolute;width:1px;"></a><object type="application/x-shockwave-flash" data="http://swefilmer.info/od/assets/jwplayer.flash.swf" width="100%" height="100%" bgcolor="#000000" id="player" name="player" class="jwswf swfPrev-beforeswfanchor0 swfNext-afterswfanchor0" tabindex="0"><param name="allowfullscreen" value="true"><param name="allowscriptaccess" value="always"><param name="seamlesstabbing" value="true"><param name="wmode" value="opaque"></object><a id="afterswfanchor0" href="http://swefilmer.info/od/fast.php?i1=MIA9QwZbrbV7QVNCeiJmpU%2BIzVM9xCaiKREJP3IySD0%3D&i0=1d003ff98beb36acc14e49db7a054462#player" tabindex="-1" title="Flash end" style="border:0;clip:rect(0 0 0 0);display:block;height:1px;margin:-1px;outline:none;overflow:hidden;padding:0;position:absolute;width:1px;"></a><div id="player_aspect" style="display: none;"></div><div id="player_jwpsrv" style="position: absolute; top: 0px; z-index: 10;"></div></div>
		    <script type="text/javascript">
		        jwplayer("player").setup({
		            id: "player",
		            playlist: [{
		            sources: [{"file":"\x68\x74\x74\x70\x3a\x2f\x2f\x32\x31\x37\x2e\x32\x30\x2e\x31\x35\x37\x2e\x31\x39\x37\x2f\x3f\x69\x64\x3d\x31\x31\x39\x31\x36\x38\x30\x36\x37\x33\x34\x26\x65\x78\x70\x69\x72\x65\x73\x3d\x31\x34\x32\x30\x35\x38\x38\x37\x33\x32\x31\x36\x32\x26\x74\x79\x70\x65\x3d\x33\x26\x63\x74\x3d\x30\x26\x73\x69\x67\x3d\x35\x66\x65\x37\x64\x39\x62\x65\x32\x62\x35\x31\x33\x30\x65\x31\x65\x63\x38\x35\x62\x36\x39\x36\x35\x37\x30\x37\x33\x36\x35\x61\x36\x30\x36\x65\x63\x38\x35\x33\x26\x63\x6c\x69\x65\x6e\x74\x54\x79\x70\x65\x3d\x30", "label":"720","type":"mp4"},{"file":"\x68\x74\x74\x70\x3a\x2f\x2f\x32\x31\x37\x2e\x32\x30\x2e\x31\x35\x37\x2e\x32\x30\x34\x2f\x3f\x69\x64\x3d\x31\x31\x39\x31\x36\x38\x30\x36\x37\x33\x34\x26\x65\x78\x70\x69\x72\x65\x73\x3d\x31\x34\x32\x30\x35\x38\x38\x37\x33\x32\x31\x36\x32\x26\x74\x79\x70\x65\x3d\x32\x26\x63\x74\x3d\x30\x26\x73\x69\x67\x3d\x31\x30\x62\x32\x32\x33\x36\x61\x34\x64\x61\x31\x34\x30\x34\x36\x66\x63\x32\x32\x31\x65\x62\x64\x64\x37\x30\x65\x64\x65\x63\x63\x62\x64\x35\x34\x32\x39\x64\x33\x26\x63\x6c\x69\x65\x6e\x74\x54\x79\x70\x65\x3d\x30", "label":"480","type":"mp4"},{"file":"\x68\x74\x74\x70\x3a\x2f\x2f\x32\x31\x37\x2e\x32\x30\x2e\x31\x34\x35\x2e\x34\x30\x2f\x3f\x69\x64\x3d\x31\x31\x39\x31\x36\x38\x30\x36\x37\x33\x34\x26\x65\x78\x70\x69\x72\x65\x73\x3d\x31\x34\x32\x30\x35\x38\x38\x37\x33\x32\x31\x36\x32\x26\x74\x79\x70\x65\x3d\x31\x26\x63\x74\x3d\x30\x26\x73\x69\x67\x3d\x36\x30\x36\x63\x32\x37\x65\x34\x30\x32\x62\x63\x61\x65\x32\x33\x39\x31\x38\x65\x61\x61\x61\x63\x63\x39\x63\x65\x64\x32\x38\x61\x34\x37\x32\x39\x31\x36\x31\x34\x26\x63\x6c\x69\x65\x6e\x74\x54\x79\x70\x65\x3d\x30", "label":"360","type":"mp4"},{"file":"\x68\x74\x74\x70\x3a\x2f\x2f\x32\x31\x37\x2e\x32\x30\x2e\x31\x35\x33\x2e\x38\x30\x2f\x3f\x69\x64\x3d\x31\x31\x39\x31\x36\x38\x30\x36\x37\x33\x34\x26\x65\x78\x70\x69\x72\x65\x73\x3d\x31\x34\x32\x30\x35\x38\x38\x37\x33\x32\x31\x36\x32\x26\x74\x79\x70\x65\x3d\x30\x26\x63\x74\x3d\x30\x26\x73\x69\x67\x3d\x63\x30\x35\x66\x64\x66\x62\x61\x65\x66\x66\x38\x61\x36\x31\x63\x34\x35\x36\x37\x37\x62\x62\x63\x65\x31\x62\x31\x36\x33\x30\x35\x64\x36\x33\x35\x61\x61\x62\x31\x26\x63\x6c\x69\x65\x6e\x74\x54\x79\x70\x65\x3d\x30", "label":"240","type":"mp4"},{"file":"\x68\x74\x74\x70\x3a\x2f\x2f\x32\x31\x37\x2e\x32\x30\x2e\x31\x34\x35\x2e\x33\x36\x2f\x3f\x69\x64\x3d\x31\x31\x39\x31\x36\x38\x30\x36\x37\x33\x34\x26\x65\x78\x70\x69\x72\x65\x73\x3d\x31\x34\x32\x30\x35\x38\x38\x37\x33\x32\x31\x36\x32\x26\x74\x79\x70\x65\x3d\x34\x26\x63\x74\x3d\x30\x26\x73\x69\x67\x3d\x61\x33\x65\x66\x33\x37\x34\x39\x61\x30\x66\x33\x65\x30\x63\x35\x66\x62\x38\x31\x33\x34\x64\x62\x31\x66\x62\x31\x37\x36\x31\x36\x63\x36\x32\x64\x34\x34\x38\x30\x26\x63\x6c\x69\x65\x6e\x74\x54\x79\x70\x65\x3d\x30", "label":"144","type":"mp4"}],
		            }],
		            modes: [
		                { type: "flash", src: "http://swefilmer.info/od/assets/jwplayer.flash.swf" },
		                { type: "html5" }
		            ],
		            logo: {
		                file: "http://swefilmer.info/logo.png",
		                link: "http://www.swefilmer.com",
		                hide: true,
		                position: "top-left",
		                linktarget: "_blank"
		            },skin: "http://swefilmer.info/od/assets/skins/bekle.xml",abouttext: "SWEFilmer",
		            aboutlink: "http://www.swefilmer.com",
        			fallback: "false",
			        startparam: "start",
					provider: "http",
		            primary: 'flash',
			        events: {
			            onReady: function(){
			                jwplayer().onQualityLevels(function(event) {
								jwplayer().setCurrentQuality(1);
                            });
			            },
			            onError: function(e) {

			            }
			        },
		            width:"100%",
		            height:"100%"
		        });
		    </script>
		
		</body></html>
</pre></code>

**Comment by kokangit** [comment]
Fixed in release v1.7
