### ISSUE TITLE
I got error that the movie is gone to many movies in this plugin.

### ISSUE THREAD

**Issue by peso1** [kokangit/xbmc-swefilmer#12]
I got error that the movie is gone (Filmen kan vara borttagen) to many movies in this plugin.
But thay work in the website.
I have tested the Movie in the Web site both befor and after I got the fail in XBMC.
Setting is that I have a account configured in XBMC for the site and Iäm logged in with the accout also when I test on the website. The resulition settning is set to higest posible.
I have used the first player "Player" option in the website in all this tests.
I have test this in both Kodi (release) in Android (Both in a Samsung Galaxy SIII G4 and Samsung Tab 4 SM-T530) and Latest 13.2 Gotham Raspxmb on a Raspberry PI.
Same truble in  both.
Tested with both plugin version 1.4 and 1.7 still same problem.

Some examples with links to the website:
Lucie (2014) http://www.swefilmer.com/lucy-2014/lucy-2014-video_671b2412f.html

The Anomaly (2014) http://www.swefilmer.com/the-anomaly-2014/the-anomaly-2014-video_7c26ed96a.html

The Machine (2013) http://www.swefilmer.com/the-machine-2013/the-machine-2013-video_17ab88ecb.html

The Last Day on Mars (2013) http://www.swefilmer.com/the-last-days-on-mars-2013/the-last-days-on-mars-2013-video_69675ac96.html

Battle of the Ardennes - Fury (2014) http://www.swefilmer.com/ardennes-fury-2014/battle-of-the-ardennes-fury-2014-video_21d3fec98.html

1939 Battle of Westerplatte (2013) http://www.swefilmer.com/tajemnica-westerplatte-2013/1939-battle-of-westerplatte-2013-video_59c012b8f.html

Det sjunde inseglet (1957) http://www.swefilmer.com/det-sjunde-inseglet-1957/det-sjunde-inseglet-1957-video_b78d72a9e.html

Repmånad (1979) http://www.swefilmer.com/repmanad-1979/repmanad-1979-video_352fac90b.html

Predikanten (2007) http://www.swefilmer.com/predikanten-2007/predikanten-2007-video_32e0fce75.html

The Adventurer: The Curse of the Midas Box (2014) http://www.swefilmer.com/the-adventurer-the-curse-of-the-midas-box-2014/the-adventurer-the-curse-of-the-midas-box-2014-video_c5e40fc7b.html

Santa Claws (2014) http://www.swefilmer.com/santa-claws-2014/santa-claws-2014-video_4d48bea6e.html

Sex Tape (2014) http://www.swefilmer.com/sex-tape-2014/sex-tape-2014-video_d37ff2b0b.html

Arrow S03E09 http://www.swefilmer.com/arrow-s03e09/arrow-s03e09-video_1f5424a04.html

Band of Brothers E08 http://www.swefilmer.com/band-of-brothers-e08/band-of-brothers-e08-video_90571861b.html

Breaking Bad S05E16 http://www.swefilmer.com/breaking-bad-s05e16/breaking-bad-s05e16-video_aa3346037.html

Bron S02E10 http://www.swefilmer.com/bron-s02e10/bron-s02e10-video_823b60dd8.html

Dexter S08E12 http://www.swefilmer.com/dexter-s08e12/dexter-s08e12-video_93c361bf3.html

The Big Bang Theory S08E09 http://www.swefilmer.com/the-big-bang-theory-s08e09/the-big-bang-theory-s08e09-video_deab068fa.html

**Comment by kokangit** [comment]
OK, thanks for the report, I can confirm that I have the same problem. I will try to fix this soon.

**Comment by kokangit** [comment]
Fixed in release v1.8
