### ISSUE TITLE
Lite strul med Swefilmer idag.

### ISSUE THREAD

**Issue by Boxedsolutions** [kokangit/xbmc-swefilmer#14]
Gjorde en quick fix lokalt. 
ändrade denna från:
html = self.yazyaz(garble[0])

till 
html = self.yazyaz(garble[1])

Då jag märkte att jwplayer elementet som regexpas inte var enligt standard på page1 så jag använde page2 istället.

**Comment by kokangit** [comment]
OK, vilken film? Lättare att reproducera felet då.

**Comment by Boxedsolutions** [comment]
Dum och dummare to. Felet är att Det saknas unicodead file: i sources objektet.

En ide vore ju att kolla först id taggen page1 och jämföra med syntax och sen om det inte funkar använda page2. 

Lite info från loggen:
20:50:32 T:2818569280  NOTICE: found garbled player
20:50:32 T:2818569280  NOTICE: scrape_video: html=<iframe scrolling="no" src="http://bg63mnprwihuqao8.vkfix.com/video_ext.php?site=swefilmer.com&amp;license=5b385f04babab00a8ba54e9f5aeb7e3e&amp;oid=249360184&id=171302549&hash=72282cde2c1e6c49&hd=1" width="500" height="370" frameborder="0"></iframe>
20:50:32 T:2818569280  NOTICE: scrape_video: url=http://bg63mnprwihuqao8.vkfix.com/video_ext.php?site=swefilmer.com&license=5b385f04babab00a8ba54e9f5aeb7e3e&oid=249360184&id=171302549&hash=72282cde2c1e6c49&hd=1
20:50:32 T:2818569280  NOTICE: get_url (document.html): http://bg63mnprwihuqao8.vkfix.com/video_ext.php?site=swefilmer.com&license=5b385f04babab00a8ba54e9f5aeb7e3e&oid=249360184&id=171302549&hash=72282cde2c1e6c49&hd=1
20:50:33 T:2818569280  NOTICE: get_url (vkfixz.html): http://zlom1p62ejg3945n.vkban.com/video_ext.php?site=swefilmer.com&license=5b385f04babab00a8ba54e9f5aeb7e3e&oid=249360184&id=171302549&hash=72282cde2c1e6c49&hd=1
20:50:34 T:2818569280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/xbmc-swefilmer-1.8/default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "/home/pi/.kodi/addons/xbmc-swefilmer-1.8/navigation.py", line 238, in dispatch
                                                ret = self.video()
                                              File "/home/pi/.kodi/addons/xbmc-swefilmer-1.8/navigation.py", line 181, in video
                                                result = self.swefilmer.scrape_video(html)
                                              File "/home/pi/.kodi/addons/xbmc-swefilmer-1.8/swefilmer.py", line 244, in scrape_video
                                                return name, description, img, self.scrape_video_jwplayer(document)
                                              File "/home/pi/.kodi/addons/xbmc-swefilmer-1.8/swefilmer.py", line 305, in scrape_video_jwplayer
                                                names = re.findall('"label":"(.+?)"', sources[0])
                                            IndexError: list index out of range

**Comment by Boxedsolutions** [comment]
De verkar mer och mer gå över till att använda en Callback funktion i javascript som hämtas via xhr, på en del vk filmer. 

De skickar med parametrar som oid, video_id, embed_hash samt callback = callbackFunc
embed_hash finns i iframe url
oid går att parsa fram i iframe url.
video_id får man också fram genom att parsa iframe url

Exempel url där kvalitetsurl ligger: https://api.vk.com/method/video.getEmbed?oid=234031247&video_id=171016675&embed_hash=1b92f18496af54a3&callback=callbackFunc

Så får man köra en re.findall('"url[0-9].+?:"(.+?)"',result) Så bör man få fram Url.
Jag är inte jättebra på python. Första gången jag tittar i ett sånt projekt. Men man för väl även i pyton kunna fånga mer än ett avsnitt med regexp?

**Comment by Boxedsolutions** [comment]
Har testat denna funktion nu och den verkar funka. 

Man bör ha en check efter self.vkfixz funktionen för att kolla om sources: [(.+?)] existerar. Gör det inte det så kör denna funktionen. 
def vkfix_scrape(self, document):
        self.xbmc.log(document)
        #urlJs = re.findall("'src',\+s?'(.+?)'",document)
        #self.xbmc.log('urlJs='+urlJs[0])
        oid = re.findall("param\[5\]\s?\+\s?'(.+?)'",document)
        videoId = re.findall("param\[6\]\s?\+\s?'(.+?)'",document)
        hash = re.findall("param\[7\]\s?\+\s?'(.+?)'",document)
        urlQ = 'https://api.vk.com/method/video.getEmbed?oid=' + oid[0] +'&video_id='+videoId[0]+'&embed_hash='+hash[0]+'&callback=callbackFunc'
        documentQ = self.get_url(urlQ,'special.html');
        urls = re.findall('"url([0-9]+?)":"(.+?)"',documentQ)
        
        #names = re.findall('"url([0-9].+?)"',document)
        self.xbmc.log('debug; '+str(urls))
    
        #self.xbmc.log(urls[0][1])
        if urls:
            return urls
        else:
            return False

**Comment by kokangit** [comment]
Tack! Det där funkade bra!
