### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Robban67** [kokangit/xbmc-swefilmer#15]
My swefilmer addon is getting script error when i try to load a movie, can it be fixed? I use your latest 1.9

**Comment by kokangit** [comment]
Möjligen om du ger mig mer info. Vilken/vilka filmer? Upprepas varje gång?

**Comment by phalax** [comment]
Samma för mig, senaste 1.9.
Samtliga filmer.
I topplistan står det "Filmen kan vara borttagen".
I nya får jag skript fel.

Det går att söka, men resultat av att försöka spela upp är skript fel.

Testar även via webbläsaren, verkar dock inte funka där heller.

Förmodligen server strul.

Kan någon mer bekräfta? Sitter på Android, har strulat en del i webbläsaren
innan.
Den 3 mar 2015 18:49 skrev "kokangit" <notifications@github.com>:

**Comment by phalax** [comment]
Testade via webbläsaren igen. Ostabilt, men verkar ändå funka ibland.

**Comment by phalax** [comment]
Några rader ur KODI loggen.
Säg till om du vill ha hela.



NOTICE: get_url (video.html): http://www.swefilmer.com/ida-2013/ida-2013-video_8fcbe7450.html
18:57:20 T:140433429255936  NOTICE: scrape_video: description=['Ida \xc3\xa4r en svart-vit polsk dramafilm fr\xc3\xa5n 2013 i regi av Pawe\xc5\x82 Pawlikowski. Pawlikowski har \xc3\xa4ven skrivit filmens manus tillsammans med Rebecca Lenkiewicz och i huvudrollen som Anna finns Agata Trzebuchowska.']
18:57:20 T:140433429255936  NOTICE: scrape_video: img=['http://i59.tinypic.com/2j60k86.jpg']
18:57:20 T:140433429255936  NOTICE: scrape_video: url=//www.facebook.com/plugins/like.php?href=&send=false&layout=standard&width=380&show_faces=false&action=like&colorscheme=dark&font&height=35
18:57:20 T:140433429255936  NOTICE: get_url (document.html): //www.facebook.com/plugins/like.php?href=&send=false&layout=standard&width=380&show_faces=false&action=like&colorscheme=dark&font&height=35
18:57:20 T:140433429255936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: //www.facebook.com/plugins/like.php?href=&send=false&layout=standard&width=380&show_faces=false&action=like&colorscheme=dark&font&height=35
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 248, in dispatch
                                                ret = self.video()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 191, in video
                                                result = self.swefilmer.scrape_video(html)
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/swefilmer.py", line 240, in scrape_video
                                                document = self.get_url(url, 'document.html')
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/swefilmer.py", line 59, in get_url
                                                response = urllib2.urlopen(req, data)
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.5/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.5/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 392, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.5/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 254, in get_type
                                            ValueError: unknown url type: //www.facebook.com/plugins/like.php?href=&send=false&layout=standard&width=380&show_faces=false&action=like&colorscheme=dark&font&height=35
                                            -->End of Python script error report<--
18:57:20 T:140434623707008   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.swefilmer/?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fida-2013%2Fida-2013-video_8fcbe7450.html&logged_in=True]
18:57:23 T:140433429255936  NOTICE: Thread BackgroundLoader start, auto delete: false
18:57:24 T:140434623707008  NOTICE: Samba is idle. Closing the remaining connections
18:57:25 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:25 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:26 T:140433904604928  NOTICE: Thread BackgroundLoader start, auto delete: false
18:57:27 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:27 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:28 T:140433429255936  NOTICE: get_url (categories.html): http://www.swefilmer.com/
18:57:31 T:140433429255936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: need more than 0 values to unpack
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 242, in dispatch
                                                ret = self.categories_menu()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 138, in categories_menu
                                                ret, pagination = self.swefilmer.scrape_categories(html)
                                            ValueError: need more than 0 values to unpack
                                            -->End of Python script error report<--
18:57:31 T:140434623707008   ERROR: GetDirectory - Error getting plugin://plugin.video.swefilmer/?action=categories&logged_in=True
18:57:31 T:140434623707008   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.swefilmer/?action=categories&logged_in=True) failed
18:57:31 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:31 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:32 T:140433904604928  NOTICE: Thread BackgroundLoader start, auto delete: false
18:57:34 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:34 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:34 T:140433429255936  NOTICE: get_url (categories.html): http://www.swefilmer.com/
18:57:35 T:140433429255936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: need more than 0 values to unpack
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 242, in dispatch
                                                ret = self.categories_menu()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 138, in categories_menu
                                                ret, pagination = self.swefilmer.scrape_categories(html)
                                            ValueError: need more than 0 values to unpack
                                            -->End of Python script error report<--
18:57:35 T:140434623707008   ERROR: GetDirectory - Error getting plugin://plugin.video.swefilmer/?action=categories&logged_in=True
18:57:35 T:140434623707008   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.swefilmer/?action=categories&logged_in=True) failed
18:57:35 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:35 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:35 T:140433904604928  NOTICE: Thread BackgroundLoader start, auto delete: false
18:57:42 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:42 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:42 T:140433429255936  NOTICE: get_url (categories.html): http://www.swefilmer.com/
18:57:43 T:140433429255936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: need more than 0 values to unpack
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 242, in dispatch
                                                ret = self.categories_menu()
                                              File "/storage/.kodi/addons/xbmc-swefilmer-master/navigation.py", line 138, in categories_menu
                                                ret, pagination = self.swefilmer.scrape_categories(html)
                                            ValueError: need more than 0 values to unpack
                                            -->End of Python script error report<--
18:57:43 T:140434623707008   ERROR: GetDirectory - Error getting plugin://plugin.video.swefilmer/?action=categories&logged_in=True
18:57:43 T:140434623707008   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.swefilmer/?action=categories&logged_in=True) failed
18:57:43 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:43 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:57:43 T:140433904604928  NOTICE: Thread BackgroundLoader start, auto delete: false
18:57:47 T:140433429255936  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:47 T:140433429255936  NOTICE: -->Python Interpreter Initialized<--
18:58:00 T:140433429255936  NOTICE: get_url (search.html): http://www.swefilmer.com/search.php?keywords=musse
18:58:03 T:140433904604928  NOTICE: Thread BackgroundLoader start, auto delete: false
18:58:14 T:140433904604928  NOTICE: Thread LanguageInvoker start, auto delete: false
18:58:14 T:140433904604928  NOTICE: -->Python Interpreter Initialized<--
18:58:14 T:140433904604928  NOTICE: get_url (video.html): http://www.swefilmer.com/house-of-mouse-halloween-special/hos-musse-halloween-special-video_825ba23be.html
18:58:15 T:140433904604928  NOTICE: scrape_video: description=['I centrum f\xc3\xb6r serien st\xc3\xa5r Disneys mest k\xc3\xa4nda figurer, som alla har en viktig roll att fylla p\xc3\xa5 nattklubben. Musse Pigg \xc3\xa4r Hos Musses chef och presenterar kortfilmer f\xc3\xb6r publiken och Mimmi Pigg h\xc3\xa5ller reda p\xc3\xa5 r\xc3\xa4kningarna. Kalle Anka v\xc3\xa4lkomnar alla g\xc3\xa4sterna och Kajsa Anka f\xc3\xb6rs\xc3\xa4krar sig om att de har reserverat bord. L\xc3\xa5ngben \xc3\xa4r kypare och Pluto \xc3\xa4r showens maskot. Andra anst\xc3\xa4llda \xc3\xa4r M\xc3\xa5rten G\xc3\xa5s som kock, Klasse som mekaniker, Knatte, Fnatte och Tjatte som showens musikband och Max, L\xc3\xa5ngbens son, som \xc3\xa4r den som \xc3\xb6ppnar bild\xc3\xb6rrarna n\xc3\xa4r g\xc3\xa4sterna kommer. Slutligen finns d\xc3\xa4r Klarabella, som \xc3\xa4r en riktig skvallerbytta, och Svarte-Petter som \xc3\xa4ger byggnaden och helst vill l\xc3\xa4gga ner klubben f\xc3\xb6r gott.Klubben g\xc3\xa4stas dessutom under seriens g\xc3\xa5ng av s\xc3\xa5 gott som samtliga tecknade disneykarakt\xc3\xa4rer fr\xc3\xa5n filmer och TV-serier - en komplett lista skulle d\xc3\xa4rf\xc3\xb6r bli i det n\xc3\xa4rmaste o\xc3\xb6versk\xc3\xa5dlig.']
18:58:15 T:140433904604928  NOTICE: scrape_video: img=['http://i60.tinypic.com/20axhqp.png']
18:58:15 T:140433904604928  NOTICE: scrape_video: url=//www.facebook.com/plugins/like.php?href=&send=false&layout=standard&width=380&show_faces=false&action=like&colorscheme=dark&font&height=35
18:58:15 T:140433904604928

**Comment by kokangit** [comment]
Fixed in v1.10

**Comment by phalax** [comment]
Funkar fint. Super tack!
Den 3 mar 2015 21:01 skrev "kokangit" <notifications@github.com>:
