### ISSUE TITLE
Får forbidden.. 

### ISSUE THREAD

**Issue by Boxedsolutions** [kokangit/xbmc-swefilmer#17]
22:48:44 T:2590495808   ERROR: get_url: failed: HTTP Error 403: Forbidden
22:48:48 T:3038064640   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.swefilmer/?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fbeck-sjukhusmorden-2015%2Fbeck-sjukhusmorden-2015-video_a043d84f8.html&logged_in=True]
22:48:48 T:2836395072  NOTICE: Thread BackgroundLoader start, auto delete: false
22:49:01 T:2657604672  NOTICE: libspotify: notified main thread

Känns lite skumt faktiskt, frågan är ju om det är swe.zzz som ställer till det.

**Comment by kokangit** [comment]
Jag kan bekräfta felet. Inte problem med swe.zzz. Problemet är troligen att hitta cookies i dokumentet.

**Comment by kokangit** [comment]
Tror det här funkar nu va?
