### ISSUE TITLE
Hur gör jag?

### ISSUE THREAD

**Issue by pandanr9** [kokangit/xbmc-swefilmer#18]
Får inte swefilmer addonen att funka på min kodisom körs på rasbmc på en raspberry. Hur gör jag? Går det att få någon hjälp här?

**Comment by Boxedsolutions** [comment]
Logga in via ssh och kör en wget --no-check-certifikate http://adressen till release. Sen går du till insällningar installera tillägg från zip. Leta reda på filen i hem mappen. Klart
