### ISSUE TITLE
Some titles are not working

### ISSUE THREAD

**Issue by pacmyc** [kokangit/xbmc-swefilmer#19]
Hi.
Some movies not working, like "all is lost (2013)";

14:22:53 T:3023912960   DEBUG: OnKey: down (0xf081) pressed, action is Down
14:22:54 T:3023912960   DEBUG: Keyboard: scancode: 0x6c, sym: 0x0112, unicode: 0x0000, modifier: 0x0
14:22:54 T:3023912960   DEBUG: OnKey: down (0xf081) pressed, action is Down
14:22:54 T:2808161312   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.image_decode input port 320 output port 321 m_handle 0xaf626e00
14:22:54 T:2808161312   DEBUG: COMXCoreComponent::AllocInputBuffers component(OMX.broadcom.image_decode) - port(320), nBufferCountMin(2), nBufferCountActual(2), nBufferSize(81920), nBufferAlignmen(16)
14:22:54 T:2808161312   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.egl_render input port 220 output port 221 m_handle 0xaf646370
14:22:54 T:2808161312   DEBUG: COMXCoreComponent::UseEGLImage component(OMX.broadcom.egl_render) - port(221), nBufferCountMin(1), nBufferCountActual(1), nBufferSize(15360) nBufferAlignmen(16)
14:22:54 T:2808161312   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.image_decode handle 0xaf626e00
14:22:54 T:2808161312   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.egl_render handle 0xaf646370
14:22:54 T:2808161312   DEBUG: DecodeJpegToTexture: decoded special://masterprofile/Thumbnails/f/f420c30e.jpg 184x273
14:22:59 T:3023912960   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
14:22:59 T:3023912960   DEBUG: OnKey: return (0xf00d) pressed, action is Select
14:22:59 T:3023912960   DEBUG: OnPlayMedia plugin://plugin.video.swefilmer/?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fall-is-lost-2013%2Fall-is-lost-2013-video_4a39bb7f8.html&logged_in=True
14:22:59 T:3023912960   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
14:22:59 T:3023912960   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
14:22:59 T:3023912960   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
14:22:59 T:3023912960   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
14:22:59 T:3023912960   DEBUG: StartScript - calling plugin SweFilmer('plugin://plugin.video.swefilmer/','9','?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fall-is-lost-2013%2Fall-is-lost-2013-video_4a39bb7f8.html&logged_in=True')
14:22:59 T:2850763808  NOTICE: Thread LanguageInvoker start, auto delete: false
14:22:59 T:2850763808    INFO: initializing python engine.
14:22:59 T:3023912960   DEBUG: WaitOnScriptResult - waiting on the SweFilmer (id=12) plugin...
14:22:59 T:2850763808   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/xbmc-swefilmer-master/default.py): start processing
14:22:59 T:2850763808  NOTICE: -->Python Interpreter Initialized<--
14:22:59 T:2850763808   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/xbmc-swefilmer-master/default.py): the source file to load is "/home/osmc/.kodi/addons/xbmc-swefilmer-master/default.py"
14:22:59 T:2850763808   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/xbmc-swefilmer-master/default.py): setting the Python path to /home/osmc/.kodi/addons/xbmc-swefilmer-master:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
14:22:59 T:2850763808   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/xbmc-swefilmer-master/default.py): entering source directory /home/osmc/.kodi/addons/xbmc-swefilmer-master
14:22:59 T:2850763808   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/xbmc-swefilmer-master/default.py): instantiating addon using automatically obtained id of "plugin.video.swefilmer" dependent on version 2.1.0 of the xbmc.python api
14:22:59 T:3023912960    INFO: CheckIdle - Closing session to http://cdn18.my.mail.ru (easy=0x43802d8, multi=0xaf670a18)
14:22:59 T:2850763808   DEBUG: get_url (video.html): http://www.swefilmer.com/all-is-lost-2013/all-is-lost-2013-video_4a39bb7f8.html
14:23:00 T:2850763808   DEBUG: scrape_video: description=['L\xc3\xa5ngt ut p\xc3\xa5 havet, mitt under en soloresa \xc3\xb6ver den Indiska oceanen,\nvaknar en man av att hans segelb\xc3\xa5t tar in vatten efter en kraftig\nkollision med en container som ligger och driver i havet.']
14:23:00 T:2850763808   DEBUG: scrape_video: img=['http://cs617218.vk.me/v617218077/2008/FWMdsdpFS_4.jpg']
14:23:00 T:2850763808   DEBUG: scrape_video_urls: player=('trailerpage', 'PGlmcmFtZSB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIzNjAiIHNyYz0iLy93d3cueW91dHViZS5jb20vZW1iZWQvTGtfUjA0TGZVUVU/ZmVhdHVyZT1wbGF5ZXJfZGV0YWlscGFnZSIgZnJhbWVib3JkZXI9IjAiIGFsbG93ZnVsbHNjcmVlbj48L2lmcmFtZT4=')
14:23:00 T:2850763808   DEBUG: scrape_video_urls: player=('page1', 'PGlmcmFtZSB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIzNjAiIHNjcm9sbGluZz0ibm8iIGZyYW1lYm9yZGVyPSIwIiBzcmM9Imh0dHA6Ly92aWRlb21lZ2EudHYvdmlldy5waHA/cmVmPTA4NDA4MzA3NDA3MTA3NzA3MjA2NzA3MzA4MzA0ODA0ODA4MzA3MzA2NzA3MjA3NzA3MTA3NDA4MzA4NCZ3aWR0aD0xMDAlJmhlaWdodD0zNjAiIGFsbG93RnVsbFNjcmVlbj48L2lmcmFtZT4=')
14:23:00 T:2850763808   DEBUG: scrape_video_urls: html=<iframe width="100%" height="360" scrolling="no" frameborder="0" src="http://videomega.tv/view.php?ref=084083074071077072067073083048048083073067072077071074083084&width=100%&height=360" allowFullScreen></iframe>
14:23:00 T:2850763808   DEBUG: scrape_video_urls: url=http://videomega.tv/view.php?ref=084083074071077072067073083048048083073067072077071074083084&width=100%&height=360
14:23:00 T:2850763808   DEBUG: get_url (document.html): http://videomega.tv/view.php?ref=084083074071077072067073083048048083073067072077071074083084&width=100%&height=360
14:23:00 T:3023912960   DEBUG: DialogProgress::StartModal called
14:23:00 T:3023912960   DEBUG: ------ Window Init (DialogProgress.xml) ------
14:23:01 T:2850763808   DEBUG: scrape_video_urls: streams=None
14:23:01 T:2850763808   DEBUG: scrape_video_urls: player=('page2', 'PGlmcmFtZSBzcmM9Imh0dHBzOi8vZG9jcy5nb29nbGUuY29tL2ZpbGUvZC8wQjdVTXNTYXN0VGROV1haRlowMUVSVGxuVmxrL3ByZXZpZXciIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjM2MCI+PC9pZnJhbWU+')
14:23:01 T:2850763808   DEBUG: scrape_video_urls: html=<iframe src="https://docs.google.com/file/d/0B7UMsSastTdNWXZFZ01ERTlnVlk/preview" width="100%" height="360"></iframe>
14:23:01 T:2850763808   DEBUG: scrape_video_urls: url=https://docs.google.com/file/d/0B7UMsSastTdNWXZFZ01ERTlnVlk/preview
14:23:01 T:2850763808   DEBUG: get_url (document.html): https://docs.google.com/file/d/0B7UMsSastTdNWXZFZ01ERTlnVlk/preview
14:23:02 T:2850763808   DEBUG: scrape_video_urls: streams=None

**Comment by kokangit** [comment]
Fixed by v1.18
