### ISSUE TITLE
script fel nya filmer

### ISSUE THREAD

**Issue by Robban67** [kokangit/xbmc-swefilmer#21]
Hej ! Jag får script fel när jag försöker öppna nya filmer. Testade även att gå in via kategorier men det funkar inte heller.

**Comment by lillmorten** [comment]
Samma här med nya (men vissa filmer fungerar i kategorier)

**Comment by kokangit** [comment]
Thanks for the report! Fixed in v1.19.

**Comment by lillmorten** [comment]
Perfekt Tack !!
