### ISSUE TITLE
Verkar ha slutat fungera

### ISSUE THREAD

**Issue by maxruben** [kokangit/xbmc-swefilmer#22]
Jag har fått skriptfel på denna några dagar nu på både OSMC på RPI2 och Kodi på Windows 7. Här är debug info omkring där felet inträffar:

16:14:58 T:7824   DEBUG: CApplication::ProcessMouse: trying mouse action leftclick
16:14:58 T:7824   DEBUG: CGUIWindowVideoBase::OnPlayMedia plugin://plugin.video.swefilmer/?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fthe-face-of-an-angel-2014%2Fthe-face-of-an-angel-2014-video_912eda607.html&logged_in=True
16:14:58 T:7824   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
16:14:58 T:7824   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
16:14:58 T:7824   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin SweFilmer('plugin://plugin.video.swefilmer/','4','?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fthe-face-of-an-angel-2014%2Fthe-face-of-an-angel-2014-video_912eda607.html&logged_in=True')
16:14:58 T:7824   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the SweFilmer (id=6) plugin...
16:14:58 T:5504  NOTICE: Thread LanguageInvoker start, auto delete: false
16:14:58 T:5504    INFO: initializing python engine.
16:14:58 T:5504   DEBUG: CPythonInvoker(6, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): start processing
16:14:58 T:5504  NOTICE: -->Python Interpreter Initialized<--
16:14:58 T:5504   DEBUG: CPythonInvoker(6, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): the source file to load is "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py"
16:14:58 T:5504   DEBUG: CPythonInvoker(6, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): setting the Python path to C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
16:14:58 T:5504   DEBUG: CPythonInvoker(6, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): entering source directory C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master
16:14:58 T:5504   DEBUG: CPythonInvoker(6, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): instantiating addon using automatically obtained id of "plugin.video.swefilmer" dependent on version 2.1.0 of the xbmc.python api
16:14:58 T:5504   DEBUG: get_url (video.html): http://www.swefilmer.com/the-face-of-an-angel-2014/the-face-of-an-angel-2014-video_912eda607.html
16:14:59 T:5504   DEBUG: scrape_video: description=['B\xc3\xa5de en journalist och en dokument\xc3\xa4rfilmare jagar historien om ett mord och dess huvudmisst\xc3\xa4nkte.']
16:14:59 T:5504   DEBUG: scrape_video: img=['http://i62.tinypic.com/24pclr9.jpg']
16:14:59 T:5504   DEBUG: scrape_video_urls: player=('trailerpage', 'PGlmcmFtZSB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIzNjAiIGFsbG93ZnVsbHNjcmVlbiBzcmM9Imh0dHBzOi8vd3d3LnlvdXR1YmUuY29tL2VtYmVkL2Z6SGRyRnlKek9BP2ZlYXR1cmU9cGxheWVyX2RldGFpbHBhZ2UiIGZyYW1lYm9yZGVyPSIwIiBhbGxvd2Z1bGxzY3JlZW4+PC9pZnJhbWU+')
16:14:59 T:5504   DEBUG: scrape_video_urls: player=('page1', 'PGlmcmFtZSBhbGxvd2Z1bGxzY3JlZW4gc3JjPSJodHRwOi8vdmtmaXguY29tL3Rva2VuL3N3ZWZpbG1lci9RMjlwVW1oeVYycHpPREF5U0hRMWNIUllRV0ZNTWtWWlIwSm5NM2MxYVZoSVVtWnBZVVpoU0RkSFdtNVdiRE54V2tGV1FYVnVVR0ZTZDJnd1psbDFkbXRZVDNsd1ZtNHJRbE5qWjB0VU1tZHlNbHBGV0dWbWRTdEdiekZ2WjJwbFkxQjJRVnBNTTFKR1ZrWXpVRVZJVmtsUWRuTllZakZ4UVdJNVkyUkpXVXd4WlZKTFZVRklkMkpyVXpKTGNFVkVXRFl3VHpWM1BUMD0iIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjM2MCIgZnJhbWVib3JkZXI9IjAiIHdlYmtpdGFsbG93ZnVsbHNjcmVlbiBtb3phbGxvd2Z1bGxzY3JlZW4gYWxsb3dmdWxsc2NyZWVuPjwvaWZyYW1lPg==')
16:14:59 T:5504   DEBUG: scrape_video_urls: html=<iframe allowfullscreen src="http://vkfix.com/token/swefilmer/Q29pUmhyV2pzODAySHQ1cHRYQWFMMkVZR0JnM3c1aVhIUmZpYUZhSDdHWm5WbDNxWkFWQXVuUGFSd2gwZll1dmtYT3lwVm4rQlNjZ0tUMmdyMlpFWGVmdStGbzFvZ2plY1B2QVpMM1JGVkYzUEVIVklQdnNYYjFxQWI5Y2RJWUwxZVJLVUFId2JrUzJLcEVEWDYwTzV3PT0=" width="100%" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
16:14:59 T:5504   DEBUG: scrape_video_urls: url=http://vkfix.com/token/swefilmer/Q29pUmhyV2pzODAySHQ1cHRYQWFMMkVZR0JnM3c1aVhIUmZpYUZhSDdHWm5WbDNxWkFWQXVuUGFSd2gwZll1dmtYT3lwVm4rQlNjZ0tUMmdyMlpFWGVmdStGbzFvZ2plY1B2QVpMM1JGVkYzUEVIVklQdnNYYjFxQWI5Y2RJWUwxZVJLVUFId2JrUzJLcEVEWDYwTzV3PT0=
16:14:59 T:5504   DEBUG: get_url (document_page1.html): http://vkfix.com/token/swefilmer/Q29pUmhyV2pzODAySHQ1cHRYQWFMMkVZR0JnM3c1aVhIUmZpYUZhSDdHWm5WbDNxWkFWQXVuUGFSd2gwZll1dmtYT3lwVm4rQlNjZ0tUMmdyMlpFWGVmdStGbzFvZ2plY1B2QVpMM1JGVkYzUEVIVklQdnNYYjFxQWI5Y2RJWUwxZVJLVUFId2JrUzJLcEVEWDYwTzV3PT0=
16:14:59 T:668   DEBUG: CAESinkDirectSound::Deinitialize: Cleaning up
16:15:00 T:7824   DEBUG: DialogProgress::StartModal called
16:15:00 T:7824   DEBUG: ------ Window Init (DialogProgress.xml) ------
16:15:00 T:7824    INFO: Loading skin file: DialogProgress.xml, load type: KEEP_IN_MEMORY
16:15:00 T:5504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\navigation.py", line 286, in dispatch
                                                ret = self.video()
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\navigation.py", line 220, in video
                                                result = self.swefilmer.scrape_video(html, url)
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\swefilmer.py", line 242, in scrape_video
                                                return name, description, img, self.scrape_video_urls(players, referer)
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\swefilmer.py", line 269, in scrape_video_urls
                                                streams = self.scrape_video_jwplayer2(document)
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\swefilmer.py", line 320, in scrape_video_jwplayer2
                                                urlQ = 'https://api.vk.com/method/video.getEmbed?oid=' + oid[0] +'&video_id='+videoId[0]+'&embed_hash='+hash[0]+'&callback=callbackFunc'
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by Robban67** [comment]
Det fungerar inte för mig heller, Kodi 13.2 på openelec.

**Comment by kokangit** [comment]
Tack för loggen! Fixat temporärt så det inte kraschar. Jobbar på att fixa den playern.

**Comment by lillmorten** [comment]
Perfekt.. Tack..

**Comment by kokangit** [comment]
Funkar väl nu?
