### ISSUE TITLE
går inte att installer på xbmc/atv2

### ISSUE THREAD

**Issue by tobe76** [kokangit/xbmc-swefilmer#23]
Säger bara installationen misslyckades.
Gäller nya ver 1.21

**Comment by lillmorten** [comment]
Fungerar perfekt här på både Kodi Rasberry PI och Ubuntu Kodi

**Comment by kokangit** [comment]
Öppna igen med mer detaljerad info om det fortfarande inte funkar. Känns inte som fel på pluginen.
