### ISSUE TITLE
Script misslyckades

### ISSUE THREAD

**Issue by Andee78** [kokangit/xbmc-swefilmer#24]
Tack för ett mycket uppskattat addon!

Har problem med de flesta nya filmer: "Script misslyckades". Exempelvis filmen "Interstellar" (men gäller samtliga(?) nya filmer tror jag).
Kör swefilmer addonet version 1.22.
Raspberry pi 2
OpenELEC 5.0.8

Logg:
http://pastebin.com/RqPSxgbC

**Comment by kokangit** [comment]
Jag lyckas inte upprepa ditt fel. Vilken "player" är det som fallerar? Har du provat olika? Jag vet att player som heter 217... och 220... aldrig funkar och även megatv misslyckas, men andra brukar funka.

**Comment by Smoke69** [comment]
Jag har samma problem ny filmer scriptfel TV serier dom äldre funkar. Vilken player vet jag ej kör helix 14.2 hybrid till boxee box intern installation

**Comment by Andee78** [comment]
Hej igen! Tack för respons. Antar att du menar det alternativ/"players" som dyker upp då man väljer en film? Jag får inte ens några alternativ på dessa filmer, dessa får jag "Script misslyckades" på direkt...

Inga hokuspokus tricks man kan pröva? :)

**Comment by kokangit** [comment]
Jag misstänker att det skulle kunna vara överbelastning på swefilmer eller filmsajterna. Kanske det hanteras bättre av javascript i webbrowser och funkar där.
Men jag har gjort lite bättre felhantering där så den skippar den playern om den strular.
För mig funkar det oftast. Ibland, särskilt under helgerna så kan det strula tycker jag mig ha märkt.

**Comment by Andee78** [comment]
Okej. Ska pröva den nya versionen och återkommer. Tror inte det har med överbelastning att göra då jag testat vid många olika tidpunkter/dagar. 

Tack så mycket! :+1:

**Comment by Andee78** [comment]
Testade nya versionen precis, men får Script fel direkt när jag försöker öppna swefilmer (svart stor ruta och Script misslyckades). Återkommer med loggfil...

**Comment by kokangit** [comment]
Gärna loggfil med debug påslagen. Just nu verkar swefilmer ligga nere, kanske är det som är felet.

**Comment by Andee78** [comment]
Ja, upptäckte precis det :) återkommer när jag testat med ett fungerade swefilmer.com...

**Comment by Andee78** [comment]
Nu verkar det faktiskt fungera som det ska! Grymt jobbat! Tusen tack för hjälpen! :+1:

**Comment by Andee78** [comment]
Märkligt, det funkade fint en gång, man fick upp ruta om vilken player och filmerna funkade som de skulle. Idag när jag prövar så får jag scriptfel så fort jag kör swefilmer addonen? Swefilmer.com verkar funka.

Logg: http://pastebin.com/1s4rtPjB

**Comment by Andee78** [comment]
Idag är det tyvärr ingen framgång... Oavsett vilket version jag prövar så får jag script misslyckades när jag ska öppna addonen... Det ser ut som att swefilmer lagt till en splashsida som kollar webbläsare etc innan man kommer in på den verkliga sidan, kan detta ha något med saken att göra? Fungerar det för dig idag?

11:14:48 T:1351611456   DEBUG: ***** _get_url (login.html) referer=None: http://www.swefilmer.com/login.php
11:14:48 T:1351611456   ERROR: ***** _get_url: failed: HTTP Error 503: Service Temporarily Unavailable

Fullständig logg:
http://pastebin.com/C7vuetYx

**Comment by maxruben** [comment]
Jag får nu också script misslyckades direkt när jag försöker gå in på swefilmer. Enligt loggfilen så får jag HTTP Error 503: Service temporarily unavailable. Men när jag går in med IE eller crome på windows så fungerar det. Det kommer först upp en sida som jag inte har sett förut (brukar dock inte titta via windows och browser direkt). Det står något om att Kontrollerar din browser. Denna sida går efter några sekunder vidare till inloggningssidan.

Från loggfil med debug aktiverat:
11:07:17 T:7780   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/ImageLib.dll)
11:07:18 T:10524   DEBUG: CApplication::ProcessMouse: trying mouse action leftclick
11:07:18 T:10524   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.swefilmer/)
11:07:18 T:10524   DEBUG:   ParentPath = [addons://sources/video/]
11:07:18 T:8904   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin SweFilmer('plugin://plugin.video.swefilmer/','1','')
11:07:18 T:8904   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the SweFilmer (id=3) plugin...
11:07:18 T:10024  NOTICE: Thread LanguageInvoker start, auto delete: false
11:07:18 T:10024    INFO: initializing python engine.
11:07:18 T:10024   DEBUG: CPythonInvoker(3, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): start processing
11:07:18 T:10024  NOTICE: -->Python Interpreter Initialized<--
11:07:18 T:10024   DEBUG: CPythonInvoker(3, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): the source file to load is "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py"
11:07:18 T:10024   DEBUG: CPythonInvoker(3, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): setting the Python path to C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
11:07:18 T:10024   DEBUG: CPythonInvoker(3, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): entering source directory C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master
11:07:18 T:10024   DEBUG: CPythonInvoker(3, C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py): instantiating addon using automatically obtained id of "plugin.video.swefilmer" dependent on version 2.1.0 of the xbmc.python api
11:07:18 T:10024   DEBUG: ***** _get_url (login.html) referer=None: http://www.swefilmer.com/login.php
11:07:18 T:10024   ERROR: ***** _get_url: failed: HTTP Error 503: Service Temporarily Unavailable
11:07:18 T:10024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\default.py", line 14, in <module>
                                                navigation.dispatch()
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\navigation.py", line 274, in dispatch
                                                ret = self.start_menu()
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\navigation.py", line 117, in start_menu
                                                logged_in = self.swefilmer.login(username, password)
                                              File "C:\Users\Ruben\AppData\Roaming\Kodi\addons\xbmc-swefilmer-master\swefilmer.py", line 128, in login
                                                if html.find('<div class="error_msg') > -1:
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
11:07:18 T:10024    INFO: Python script stopped
11:07:18 T:10024   DEBUG: Thread LanguageInvoker 10024 terminating
11:07:18 T:8904   DEBUG:  XFILE::CPluginDirectory::WaitOnScriptResult - plugin exited prematurely - terminating
11:07:18 T:10524   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.swefilmer/
11:07:18 T:10524   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.swefilmer/) failed
11:07:18 T:10524   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video/)

**Comment by Smoke69** [comment]
Jag får exakt samma fel både på mina 3 Boxee box samt min TLBB skall testa raspen

**Comment by lillmorten** [comment]
Fungerar perfekt under Ubuntu/Kodi ??

**Comment by kokangit** [comment]
HTTP Error 503 från swefilmer: tror det är cloudflare som strular. Kollar på det.

**Comment by lillmorten** [comment]
Fungerar även perfekt på Rasberry PI (Open elect /  Kodi)

**Comment by maxruben** [comment]
Tittade precis på en serie och det fungerade också. Märkte att det fanns betydligt fler källor (player?) att välja ifrån men väldigt få eller bara en fungerade.

**Comment by Smoke69** [comment]
Tusen tack kokangit för allt jobb du lågt ner på denna underbara addonen. Nu funkar allt som det skall har inga som helst problem nu. Änn en gång massor av tack

**Comment by olsson74** [comment]
Instämmer med föregående talare, tusen tack!!

**Comment by lillmorten** [comment]
Men vad nu då version 1.24 fungerar inte för mig... medans 1.23 fungerade perfekt (Kodi rasberry pi)  ?  kokangit  kan du posta 1.23 igen i något bibliotek ?

**Comment by Smoke69** [comment]
Swefilmer ligger nere just nu så jag tror att det är det som är problemet

**Comment by lillmorten** [comment]
Ops.. Kanske  skulle kolla det först.. Tack..Smoke69

**Comment by peso1** [comment]
Enligt rycken flyttar Swefilmer till DreamfilmsHD.org
Kommer detta plugin at uppdateras? Det gamla Dreamfils pluginet har ju inte uppdateras sedan Januari i år och fungerar därför inte.

https://www.facebook.com/pages/Swefilmercom/327326977387431

**Comment by kokangit** [comment]
Ja, jag tror att jag kommer fortsätta att försöka få denna plugin att fungera även i framtiden.

**Comment by Andee78** [comment]
kokangit: Tusen tack för updaten! Fungerar utmärkt nu!
peso1: DreamFilm addonen är även den uppdaterad och fungerar som den ska...
