### ISSUE TITLE
Add to repository

### ISSUE THREAD

**Issue by daniel-lundin** [kokangit/xbmc-swefilmer#3]
Hi,

I'm thinking about creating a xbmc-repository for swedish streaming addons.
Do you have your addon published to any repository?

Maybe we can discuss this further via email: d-dog@d-dog.se

**Comment by peso1** [comment]
+1 for the idea and to make it hopfully outoupdate thrue Kodi.

**Comment by HenrikNyberg** [comment]
+1 for the idea

**Comment by kokangit** [comment]
I created a repository (kokangit/xbmc-swe-repo) and added this plugin.

**Comment by HenrikNyberg** [comment]
Någon anledning till att inte kalla den för kodi?
Den 7 mar 2015 20:38 skrev "kokangit" <notifications@github.com>:

**Comment by kokangit** [comment]
Näe, bara gammal vana.
