### ISSUE TITLE
Issues with playback from api.video.mail.ru

### ISSUE THREAD

**Issue by agail** [kokangit/xbmc-swefilmer#7]
First, thanks for a great addon, keep up the good work!

Seems swefilmer uses different sources for streaming content.

The scripts is having trouble to open streams from api.video.mail.ru (House of cards S01E01) 

XBMC4Xbox 3.5-BETA4-r32788 (SVN:32788, compiler 1310). Built on May 15 2014
XBMC-Swefilmer v1.3

XBMC.log - http://pastebin.com/avNtuVsb

**Comment by kokangit** [comment]
I just released v1.6 fixing this issue.
